# Generated by Django 4.0.6 on 2022-08-16 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_relationship_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_main', to='articles.article', verbose_name='Статья'),
        ),
    ]
