# Generated by Django 4.0.6 on 2022-08-16 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_relationship_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relate', to='articles.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relate', to='articles.scope', verbose_name='Раздел'),
        ),
    ]
