# Generated by Django 4.0.6 on 2022-08-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_scope_scopes_scope_scopes1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='scopes1',
            field=models.ManyToManyField(through='articles.Relationship', to='articles.article'),
        ),
    ]
