# Generated by Django 4.0.6 on 2022-08-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_scope_scopes1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='scopes1',
            field=models.ManyToManyField(related_name='scopes1', through='articles.Relationship', to='articles.article'),
        ),
    ]
