# Generated by Django 4.0.6 on 2022-08-17 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_scope_scopes1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='scopes1',
        ),
        migrations.AddField(
            model_name='scope',
            name='scopes',
            field=models.ManyToManyField(related_name='scopes', through='articles.Relationship', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.scope', verbose_name='Раздел'),
        ),
    ]
