# Generated by Django 4.0.6 on 2022-08-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_alter_measurement_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='picture',
            field=models.ImageField(default='null', max_length=20, upload_to=''),
            preserve_default=False,
        ),
    ]
