# Generated by Django 4.0.6 on 2022-08-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0011_alter_measurement_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
