# Generated by Django 4.0.6 on 2022-08-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0013_measurement_updated_at_alter_measurement_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='updated_at',
        ),
    ]
